# Funding options for this project
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [bybren-llc]
# ko_fi: wordstofilmby
# patreon: wordstofilmby
custom: ["https://wordstofilmby.com/sponsor"]
